version: '3.7'
services:
  php:
    container_name: ${COMPOSE_PROJECT_NAME}_PHP
    build:
      context: ./php
      args:
        PHP_EXTENSIONS: ${PHP_EXTENSIONS}
        PHP_VERSION: ${PHP_VERSION}
        PHP_ALPINE: ${PHP_ALPINE}
        TIMEZONE: ${TIMEZONE}
    volumes:
      - ./app:/var/www/html

  database:
    container_name: ${COMPOSE_PROJECT_NAME}_MySQL
    platform: linux/x86_64 #obligatoire pour les users macos vu que mysql existe pas nativement sous ARM
    image: mysql:8.0.31-debian
    environment:
      MYSQL_DATABASE: projet
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "55432:3306"
    volumes:
      - db-data:/var/lib/mysql

  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}_NGINX
    build: ./nginx
    volumes:
      - ./app:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - php
    ports:
      - "80:80"
      - "443:443"

volumes:
  db-data: